// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AuthenticationRequestJSON ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AuthenticationRequestJSON ) UnmarshalJSON([]byte) error { return nil }
func ( AuthenticationRequestJSON ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AuthenticationRequestJSON ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AuthenticationRequestJSON *AuthenticationRequestJSON
