// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  domain

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Behavior ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Behavior ) UnmarshalJSON([]byte) error { return nil }
func ( Behavior ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Behavior ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Behavior *Behavior

func ( BehaviorConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BehaviorConfig ) UnmarshalJSON([]byte) error { return nil }
func ( BehaviorConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BehaviorConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BehaviorConfig *BehaviorConfig

func ( Behaviors ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Behaviors ) UnmarshalJSON([]byte) error { return nil }
func ( Behaviors ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Behaviors ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Behaviors *Behaviors

func ( BlocksServiceChannel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BlocksServiceChannel ) UnmarshalJSON([]byte) error { return nil }
func ( BlocksServiceChannel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BlocksServiceChannel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BlocksServiceChannel *BlocksServiceChannel

func ( Index ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Index ) UnmarshalJSON([]byte) error { return nil }
func ( Index ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Index ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Index *Index

func ( LayoutServiceChannel ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LayoutServiceChannel ) UnmarshalJSON([]byte) error { return nil }
func ( LayoutServiceChannel ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LayoutServiceChannel ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LayoutServiceChannel *LayoutServiceChannel

func ( QTLayout ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QTLayout ) UnmarshalJSON([]byte) error { return nil }
func ( QTLayout ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QTLayout ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QTLayout *QTLayout

func ( QTStore ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QTStore ) UnmarshalJSON([]byte) error { return nil }
func ( QTStore ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QTStore ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QTStore *QTStore

func ( Queue ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Queue ) UnmarshalJSON([]byte) error { return nil }
func ( Queue ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Queue ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Queue *Queue

func ( QueueLayout ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QueueLayout ) UnmarshalJSON([]byte) error { return nil }
func ( QueueLayout ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QueueLayout ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QueueLayout *QueueLayout

func ( QueueStore ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QueueStore ) UnmarshalJSON([]byte) error { return nil }
func ( QueueStore ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QueueStore ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QueueStore *QueueStore

func ( QueueThresholds ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QueueThresholds ) UnmarshalJSON([]byte) error { return nil }
func ( QueueThresholds ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QueueThresholds ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QueueThresholds *QueueThresholds

func ( Recommendations ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Recommendations ) UnmarshalJSON([]byte) error { return nil }
func ( Recommendations ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Recommendations ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Recommendations *Recommendations

func ( RecommendationsLayout ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RecommendationsLayout ) UnmarshalJSON([]byte) error { return nil }
func ( RecommendationsLayout ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RecommendationsLayout ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RecommendationsLayout *RecommendationsLayout

func ( ServiceChannelElement ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ServiceChannelElement ) UnmarshalJSON([]byte) error { return nil }
func ( ServiceChannelElement ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ServiceChannelElement ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ServiceChannelElement *ServiceChannelElement

func ( Store ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Store ) UnmarshalJSON([]byte) error { return nil }
func ( Store ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Store ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Store *Store
