package domain

// Code generated by defimpl for default implementation of interfaces. DO NOT EDIT.

import (
	"context"
	"git.countmax.ru/countmax/layoutconfig.api/domain/reference"
	"time"
)

// DefImplACLRepoInterface default implementation of ACLRepoInterface
type DefImplACLRepoInterface struct{}

// FindStoresByCities default implementation method of ACLRepoInterface interface
func (DefImplACLRepoInterface) FindStoresByCities(context.Context, string, string) ([]string, error) {
	panic("method FindStoresByCities not implemented")
}

// FindStoresByRegions default implementation method of ACLRepoInterface interface
func (DefImplACLRepoInterface) FindStoresByRegions(context.Context, string, string) ([]string, error) {
	panic("method FindStoresByRegions not implemented")
}

// FindStoresByCountries default implementation method of ACLRepoInterface interface
func (DefImplACLRepoInterface) FindStoresByCountries(context.Context, string, string) ([]string, error) {
	panic("method FindStoresByCountries not implemented")
}

// FindEntrances default implementation method of ACLRepoInterface interface
func (DefImplACLRepoInterface) FindEntrances(context.Context, string, string) ([]string, error) {
	panic("method FindEntrances not implemented")
}

// DefImplLayoutRepo default implementation of LayoutRepo
type DefImplLayoutRepo struct{}

// FindLayouts default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindLayouts(context.Context, string, string, int64, int64) (Layouts, int64, error) {
	panic("method FindLayouts not implemented")
}

// FindLayoutByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindLayoutByID(context.Context, string, string, string) (*Layout, error) {
	panic("method FindLayoutByID not implemented")
}

// FindChains default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChains(context.Context, string, string, string, int64, int64) (Chains, int64, error) {
	panic("method FindChains not implemented")
}

// FindChainByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainByID(context.Context, string, string, string) (*Chain, error) {
	panic("method FindChainByID not implemented")
}

// AddChain default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChain(context.Context, Chain) (string, error) {
	panic("method AddChain not implemented")
}

// DelChain default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChain(context.Context, string) (int64, error) {
	panic("method DelChain not implemented")
}

// UpdChain default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChain(context.Context, Chain, bool, string) (int64, error) {
	panic("method UpdChain not implemented")
}

// FindChainStores default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainStores(context.Context, string, string, string, string, int64, int64, string) (ChainStores, int64, error) {
	panic("method FindChainStores not implemented")
}

// FindChainStoreByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainStoreByID(context.Context, string, string, string) (*ChainStore, error) {
	panic("method FindChainStoreByID not implemented")
}

// AddChainStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChainStore(context.Context, ChainStore) (string, error) {
	panic("method AddChainStore not implemented")
}

// DelChainStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainStore(context.Context, string) (int64, error) {
	panic("method DelChainStore not implemented")
}

// UpdChainStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChainStore(context.Context, ChainStore, bool, string) (int64, error) {
	panic("method UpdChainStore not implemented")
}

// FindChainEntrances default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainEntrances(context.Context, string, string, string, string, string, string, int64, int64) (ChainEntrances, int64, error) {
	panic("method FindChainEntrances not implemented")
}

// FindChainEntranceByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainEntranceByID(context.Context, string, string, string) (*ChainEntrance, error) {
	panic("method FindChainEntranceByID not implemented")
}

// AddChainEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChainEntrance(context.Context, ChainEntrance) (string, error) {
	panic("method AddChainEntrance not implemented")
}

// DelChainEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainEntrance(context.Context, string) (int64, error) {
	panic("method DelChainEntrance not implemented")
}

// UpdChainEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChainEntrance(context.Context, ChainEntrance, bool, string) (int64, error) {
	panic("method UpdChainEntrance not implemented")
}

// FindChainZones default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZones(context.Context, string, string, string, string, string, string, string, string, int64, int64) (ChainZones, int64, error) {
	panic("method FindChainZones not implemented")
}

// FindChainZoneByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZoneByID(context.Context, string, string, string) (*ChainZone, error) {
	panic("method FindChainZoneByID not implemented")
}

// AddChainZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChainZone(context.Context, ChainZone) (string, error) {
	panic("method AddChainZone not implemented")
}

// DelChainZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainZone(context.Context, string) (int64, error) {
	panic("method DelChainZone not implemented")
}

// UpdChainZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChainZone(context.Context, ChainZone, bool, string) (int64, error) {
	panic("method UpdChainZone not implemented")
}

// FindChainDevices default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainDevices(context.Context, string, string, string, string, string, string, string, string, string, int64, int64) (ChainDevices, int64, error) {
	panic("method FindChainDevices not implemented")
}

// FindChainDeviceByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainDeviceByID(context.Context, string, string, string) (*ChainDevice, error) {
	panic("method FindChainDeviceByID not implemented")
}

// AddChainDevice default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChainDevice(context.Context, ChainDevice) (string, error) {
	panic("method AddChainDevice not implemented")
}

// DelChainDevice default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainDevice(context.Context, string) (int64, error) {
	panic("method DelChainDevice not implemented")
}

// UpdChainDevice default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChainDevice(context.Context, ChainDevice, bool, string) (int64, error) {
	panic("method UpdChainDevice not implemented")
}

// FindChainDeviceDelays default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainDeviceDelays(context.Context, string, []string, []string) (DeviceDelayDatas, error) {
	panic("method FindChainDeviceDelays not implemented")
}

// FindChainDeviceTracks default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainDeviceTracks(context.Context, string, string, string, time.Time, time.Time, int64, int64) (Tracks, int64, error) {
	panic("method FindChainDeviceTracks not implemented")
}

// FindChainDeviceTracksAt default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainDeviceTracksAt(context.Context, string, string, string, time.Time, time.Duration) (Tracks, error) {
	panic("method FindChainDeviceTracksAt not implemented")
}

// FindChainSensors default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainSensors(context.Context, string, string, string, string, string, string, int64, int64) (ChainSensors, int64, error) {
	panic("method FindChainSensors not implemented")
}

// FindChainSensorByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainSensorByID(context.Context, string, string, string) (*ChainSensor, error) {
	panic("method FindChainSensorByID not implemented")
}

// AddChainSensor default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) AddChainSensor(context.Context, ChainSensor) (string, error) {
	panic("method AddChainSensor not implemented")
}

// DelChainSensor default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainSensor(context.Context, string) (int64, error) {
	panic("method DelChainSensor not implemented")
}

// UpdChainSensor default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdChainSensor(context.Context, ChainSensor, bool, string) (int64, error) {
	panic("method UpdChainSensor not implemented")
}

// BindChainSensorEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) BindChainSensorEntrance(context.Context, BindingChainSensorEntrance) error {
	panic("method BindChainSensorEntrance not implemented")
}

// BindChainSensorZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) BindChainSensorZone(context.Context, BindingChainSensorZone) error {
	panic("method BindChainSensorZone not implemented")
}

// BindChainEntranceZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) BindChainEntranceZone(context.Context, BindingChainEntranceZone) error {
	panic("method BindChainEntranceZone not implemented")
}

// BindChainEntranceStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) BindChainEntranceStore(context.Context, BindingChainEntranceStore) error {
	panic("method BindChainEntranceStore not implemented")
}

// FindBindChainSensorZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindBindChainSensorZone(context.Context, string, string, int64, int64) (BindingsChainSensorZone, int64, error) {
	panic("method FindBindChainSensorZone not implemented")
}

// DelChainBindSensorEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainBindSensorEntrance(context.Context, string, string) (int64, error) {
	panic("method DelChainBindSensorEntrance not implemented")
}

// DelChainBindSensorZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainBindSensorZone(context.Context, string, string) (int64, error) {
	panic("method DelChainBindSensorZone not implemented")
}

// DelChainBindEntranceZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainBindEntranceZone(context.Context, string, string) (int64, error) {
	panic("method DelChainBindEntranceZone not implemented")
}

// DelChainBindEntranceStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) DelChainBindEntranceStore(context.Context, string, string) (int64, error) {
	panic("method DelChainBindEntranceStore not implemented")
}

// UpdBindChainSensorEntrance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdBindChainSensorEntrance(context.Context, BindingChainSensorEntrance, string, bool, string) error {
	panic("method UpdBindChainSensorEntrance not implemented")
}

// UpdBindChainSensorZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdBindChainSensorZone(context.Context, BindingChainSensorZone, string, bool, string) error {
	panic("method UpdBindChainSensorZone not implemented")
}

// UpdBindChainEntranceZone default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdBindChainEntranceZone(context.Context, BindingChainEntranceZone, string, bool, string) error {
	panic("method UpdBindChainEntranceZone not implemented")
}

// UpdBindChainEntranceStore default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdBindChainEntranceStore(context.Context, BindingChainEntranceStore, string, bool, string) error {
	panic("method UpdBindChainEntranceStore not implemented")
}

// FindMalls default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMalls(context.Context, string, string, int64, int64) (Malls, int64, error) {
	panic("method FindMalls not implemented")
}

// FindMallByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallByID(context.Context, string, string, string) (*Mall, error) {
	panic("method FindMallByID not implemented")
}

// FindMallEntrances default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallEntrances(context.Context, string, string, string, string, string, string, int64, int64) (MallEntrances, int64, error) {
	panic("method FindMallEntrances not implemented")
}

// FindMallEntranceByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallEntranceByID(context.Context, string, string, string) (*MallEntrance, error) {
	panic("method FindMallEntranceByID not implemented")
}

// FindMallZones default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallZones(context.Context, string, string, string, string, string, string, string, int64, int64) (MallZones, int64, error) {
	panic("method FindMallZones not implemented")
}

// FindMallZoneByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallZoneByID(context.Context, string, string, string) (*MallZone, error) {
	panic("method FindMallZoneByID not implemented")
}

// FindMallZonesByRenter default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallZonesByRenter(context.Context, string, string, string) (MallZones, error) {
	panic("method FindMallZonesByRenter not implemented")
}

// FindRenters default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindRenters(context.Context, string, string, string, string, string, string, int64, int64) (Renters, int64, error) {
	panic("method FindRenters not implemented")
}

// FindRenterByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindRenterByID(context.Context, string, string, string) (*Renter, error) {
	panic("method FindRenterByID not implemented")
}

// FindMallDevices default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallDevices(context.Context, string, string, string, string, string, string, string, string, int64, int64) (MallDevices, int64, error) {
	panic("method FindMallDevices not implemented")
}

// FindMallDeviceByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallDeviceByID(context.Context, string, string, string) (*MallDevice, error) {
	panic("method FindMallDeviceByID not implemented")
}

// FindMallDeviceDelays default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallDeviceDelays(context.Context, string, []string) (DeviceDelayDatas, error) {
	panic("method FindMallDeviceDelays not implemented")
}

// FindMallSensors default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallSensors(context.Context, string, string, string, string, string, int64, int64) (MallSensors, int64, error) {
	panic("method FindMallSensors not implemented")
}

// FindMallSensorByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallSensorByID(context.Context, string, string, string) (*MallSensor, error) {
	panic("method FindMallSensorByID not implemented")
}

// FindZoneDataInsideDay default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindZoneDataInsideDay(context.Context, *string, *time.Time) (DatasInside, error) {
	panic("method FindZoneDataInsideDay not implemented")
}

// FindZoneDataInsideNow default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindZoneDataInsideNow(context.Context, *string) (DatasInside, error) {
	panic("method FindZoneDataInsideNow not implemented")
}

// FindZoneDataInsideRange default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindZoneDataInsideRange(context.Context, time.Time, time.Time, *string, *time.Time) (DatasInside, error) {
	panic("method FindZoneDataInsideRange not implemented")
}

// FindChainStoresDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainStoresDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (StoresAttendance, error) {
	panic("method FindChainStoresDataAttendance not implemented")
}

// FindChainZonesDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZonesDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (ZonesAttendance, error) {
	panic("method FindChainZonesDataAttendance not implemented")
}

// FindChainEntrancesDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainEntrancesDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (EntrancesAttendance, error) {
	panic("method FindChainEntrancesDataAttendance not implemented")
}

// FindMallZonesDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallZonesDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (ZonesAttendance, error) {
	panic("method FindMallZonesDataAttendance not implemented")
}

// FindMallEntrancesDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindMallEntrancesDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (EntrancesAttendance, error) {
	panic("method FindMallEntrancesDataAttendance not implemented")
}

// FindRenterDataAttendance default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindRenterDataAttendance(context.Context, time.Time, time.Time, string, string, string, string) (RentersAttendance, error) {
	panic("method FindRenterDataAttendance not implemented")
}

// FindChainStoresDataQueue default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainStoresDataQueue(context.Context, time.Time, time.Time, *string, string, string, int) (StoresDataQueue, error) {
	panic("method FindChainStoresDataQueue not implemented")
}

// FindChainStoresDataQueueNow default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainStoresDataQueueNow(context.Context, *string) (StoresDataQueue, error) {
	panic("method FindChainStoresDataQueueNow not implemented")
}

// FindChainZonesDataQueue default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZonesDataQueue(context.Context, time.Time, time.Time, string, string) (ZonesDataQueue, error) {
	panic("method FindChainZonesDataQueue not implemented")
}

// FindChainZonesDataQueueNow default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZonesDataQueueNow(context.Context, *string) (ZonesDataQueue, error) {
	panic("method FindChainZonesDataQueueNow not implemented")
}

// FindChainZonesStates default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZonesStates(context.Context, string, string, string, time.Time, time.Time, int64, int64) (ZoneStates, int64, error) {
	panic("method FindChainZonesStates not implemented")
}

// FindChainZonesStatesLast default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZonesStatesLast(context.Context, string, string, string) (ZoneStates, error) {
	panic("method FindChainZonesStatesLast not implemented")
}

// FindChainZoneStateAtTime default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainZoneStateAtTime(context.Context, string, string, time.Time) (*ZoneState, error) {
	panic("method FindChainZoneStateAtTime not implemented")
}

// FindChainPredictionQueue default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindChainPredictionQueue(context.Context, time.Time, time.Time, *string, time.Duration) (PredictionsQueue, error) {
	panic("method FindChainPredictionQueue not implemented")
}

// FindZoneDataEvaluation default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindZoneDataEvaluation(context.Context, time.Time, time.Time, string, string, string, string) (ZoneDataEvaluations, error) {
	panic("method FindZoneDataEvaluation not implemented")
}

// FindBehaviors default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindBehaviors(context.Context, int64, int64) (Behaviors, int64, error) {
	panic("method FindBehaviors not implemented")
}

// FindBehaviorByLayoutID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindBehaviorByLayoutID(context.Context, string) (*Behavior, error) {
	panic("method FindBehaviorByLayoutID not implemented")
}

// UpdBehavior default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) UpdBehavior(context.Context, string, Behavior) (int64, error) {
	panic("method UpdBehavior not implemented")
}

// FindCrossesZoneEnter default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindCrossesZoneEnter(context.Context, string, string) (BindingsEntranceZone, error) {
	panic("method FindCrossesZoneEnter not implemented")
}

// FindReports default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindReports(context.Context, string, string) (Reports, error) {
	panic("method FindReports not implemented")
}

// FindReportFiles default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindReportFiles(context.Context, string, string, string, int64, int64) (ReportFiles, int64, error) {
	panic("method FindReportFiles not implemented")
}

// FindReportFileByID default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) FindReportFileByID(context.Context, string) (*ReportFile, error) {
	panic("method FindReportFileByID not implemented")
}

// GetReferences default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetReferences(context.Context) ([]string, error) {
	panic("method GetReferences not implemented")
}

// GetRefCategories default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetRefCategories(context.Context) (reference.RefCategories, error) {
	panic("method GetRefCategories not implemented")
}

// GetRefPriceSegments default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetRefPriceSegments(context.Context) (reference.RefPrices, error) {
	panic("method GetRefPriceSegments not implemented")
}

// GetRefKindZones default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetRefKindZones(context.Context) (reference.RefKindZones, error) {
	panic("method GetRefKindZones not implemented")
}

// GetRefKindEnters default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetRefKindEnters(context.Context) (reference.RefKindEnters, error) {
	panic("method GetRefKindEnters not implemented")
}

// GetEntities default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetEntities(context.Context, string, string, string, string, int64, int64) (Entities, int64, error) {
	panic("method GetEntities not implemented")
}

// GetRepos default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetRepos(context.Context) (map[string]LayoutRepo, error) {
	panic("method GetRepos not implemented")
}

// GetSrvPortDB default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) GetSrvPortDB() string {
	panic("method GetSrvPortDB not implemented")
}

// Health default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) Health(context.Context) error {
	panic("method Health not implemented")
}

// Scope default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) Scope() string {
	panic("method Scope not implemented")
}

// Dest default implementation method of LayoutRepo interface
func (DefImplLayoutRepo) Dest() string {
	panic("method Dest not implemented")
}
